/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/topBar/breadcrumb.vue')['default']
    Dark: typeof import('./components/topBar/darkModeSwitch/dark.vue')['default']
    DarkModeSwitch: typeof import('./components/topBar/darkModeSwitch/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Home: typeof import('./components/home.vue')['default']
    I18nSwitch: typeof import('./components/topBar/i18nSwitch.vue')['default']
    Light: typeof import('./components/topBar/darkModeSwitch/light.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    Logo: typeof import('./components/topBar/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/topBar/index.vue')['default']
    User: typeof import('./components/user.vue')['default']
    UserMenu: typeof import('./components/topBar/userMenu.vue')['default']
    UtilsMenu: typeof import('./components/topBar/utilsMenu.vue')['default']
  }
}
