/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/topBar/breadcrumb.vue')['default']
    CourseDetail: typeof import('./components/courseDetail.vue')['default']
    CourseList: typeof import('./components/courseList.vue')['default']
    CoursePanel: typeof import('./components/coursePanel.vue')['default']
    Dark: typeof import('./components/topBar/darkModeSwitch/dark.vue')['default']
    DarkModeSwitch: typeof import('./components/topBar/darkModeSwitch/index.vue')['default']
    DetailPage: typeof import('./components/detailPage.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Home: typeof import('./components/home.vue')['default']
    I18nSwitch: typeof import('./components/topBar/i18nSwitch.vue')['default']
    Light: typeof import('./components/topBar/darkModeSwitch/light.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    Logo: typeof import('./components/topBar/logo.vue')['default']
    NavBar: typeof import('./components/topBar/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Star: typeof import('./components/star.vue')['default']
    Tag: typeof import('./components/tag.vue')['default']
    TopBar: typeof import('./components/topBar/index.vue')['default']
    User: typeof import('./components/user.vue')['default']
    UserMenu: typeof import('./components/topBar/userMenu.vue')['default']
    UtilsMenu: typeof import('./components/topBar/utilsMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
